package dev.zalaya.overkill.backend.infrastructure.assertions;

import dev.zalaya.overkill.backend.domain.model.Task;
import dev.zalaya.overkill.backend.infrastructure.persistence.entity.TaskEntity;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;

public class TaskEntityAssertions extends AbstractAssert<TaskEntityAssertions, TaskEntity> {

    private TaskEntityAssertions(TaskEntity actual) {
        super(actual, TaskEntityAssertions.class);
    }

    public static TaskEntityAssertions assertThat(TaskEntity actual) {
        return new TaskEntityAssertions(actual);
    }

    public TaskEntityAssertions hasExpectedDefinedFields(TaskEntity expected) {
        isNotNull();

        Assertions.assertThat(actual.getTitle()).isEqualTo(expected.getTitle());
        Assertions.assertThat(actual.getPriority()).isEqualTo(expected.getPriority());

        return this;
    }

    public TaskEntityAssertions hasAutoGeneratedFields() {
        isNotNull();

        Assertions.assertThat(actual.getId()).isNotNull();
        Assertions.assertThat(actual.getCreatedAt()).isNotNull();
        Assertions.assertThat(actual.getUpdatedAt()).isNotNull();

        return this;
    }

    public TaskEntityAssertions hasSameFieldsAs(Task expected) {
        isNotNull();

        Assertions.assertThat(actual.getTitle()).isEqualTo(expected.getTitle());
        Assertions.assertThat(actual.getDescription()).isEqualTo(expected.getDescription());
        Assertions.assertThat(actual.getPriority()).isEqualTo(expected.getPriority());
        Assertions.assertThat(actual.getExpiresAt()).isEqualTo(expected.getExpiresAt());

        return this;
    }

}
